# Generated by Django 6.1 on 2026-08-15 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_abssin'),
        ('transport', '0010_fareband_vehicle_maintenance_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='transport.organization'),
        ),
    ]
