# Generated by Django 6.1 on 2026-08-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organisation',
            new_name='organization',
        ),
    ]
