# Generated by Django 6.1 on 2026-08-15 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        ('transport', '0010_fareband_vehicle_maintenance_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='transport.trip'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='transport.vehicle'),
        ),
    ]
