# Generated by Django 6.1 on 2026-08-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaint_updated_at_alter_complaint_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('DRIVER', 'Driver behavior'), ('VEHICLE', 'Vehicle condition'), ('FARE', 'Overcharging'), ('DELAY', 'Late departure'), ('ROUTE', 'Route issue'), ('SAFETY', 'Safety concern'), ('BOOKING', 'Booking issue'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
