# Generated by Django 6.1 on 2026-08-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('distance_from_origin_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='transport.busstop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='transport.route')),
            ],
            options={
                'ordering': ['stop_order'],
                'constraints': [models.UniqueConstraint(fields=('route', 'stop_order'), name='unique_route_stop_order')],
            },
        ),
    ]
