# Generated by Django 6.1 on 2026-08-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
