# Generated by Django 6.1 on 2026-08-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['min_distance_km'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='maintenance_note',
            field=models.TextField(blank=True),
        ),
    ]
