# Generated by Django 6.1 on 2026-08-16 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_fareband_vehicle_maintenance_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boarding_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_fares', to='transport.busstop')),
                ('destination_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_fares', to='transport.busstop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='transport.route')),
            ],
            options={
                'ordering': ['boarding_stop', 'destination_stop'],
                'constraints': [models.UniqueConstraint(fields=('route', 'boarding_stop', 'destination_stop'), name='unique_route_fare')],
            },
        ),
    ]
